// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.Fireblocks.Settlement.Postgres;

#nullable disable

namespace Service.Fireblocks.Settlement.Postgres.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220124144530_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fireblocks-settlements")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.Fireblocks.Settlement.Postgres.Models.TransferEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountsInTransfers")
                        .HasColumnType("integer");

                    b.Property<string>("AsssetNetwork")
                        .HasColumnType("text");

                    b.Property<string>("AsssetSymbol")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationVaultAccountId")
                        .HasColumnType("text");

                    b.Property<string>("FireblocksAssetId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsssetSymbol", "AsssetNetwork", "Status");

                    b.ToTable("transfers", "fireblocks-settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
